name: Docker Image CI

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build the Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_HUB_USERNAME }}/vehicles-microservice:${TAG} --tag ${{ secrets.DOCKER_HUB_USERNAME }}/vehicles-microservice:latest

      - name: Push the Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vehicles-microservice:${TAG}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vehicles-microservice:latest